Main Coroutine Cleanup
odaridavid/WeatherApp pull request #34
Opened 2023-04-21 16:02 UTC by Mzazi25

## Related Issue
No Related Issue
## Description
Cleans up the deprecated TestCoroutineDispatcher and replaced with UnconfinedTestDispatcher
## How Can It Be Tested
All tests that require MainCoroutineRule runs smoothly 
## Screenshots (If Applicable)
N/A
## Additional Comments
N/A
## Checklist

- [ ] New tests were added/Existing Modified

2023-04-22 10:06 UTC, jumaallan requested changes

2023-04-22 10:06 UTC, jumaallan commented on app/src/test/java/com/github/odaridavid/weatherapp/MainCoroutineRule.kt
> +import kotlinx.coroutines.test.*
Avoid wildcard imports 😄

2023-04-22 11:49 UTC, Mzazi25 commented on app/src/test/java/com/github/odaridavid/weatherapp/MainCoroutineRule.kt
> +import kotlinx.coroutines.test.*
Fixed.

2023-04-23 12:01 UTC, odaridavid commented
Nice one @Mzazi25

2023-04-23 12:01 UTC, odaridavid approved these changes

2023-04-23 12:01 UTC, merged